# default value
spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  datasource:
    url: ${JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    ru.rsh12: debug


