version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/parser_db
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: docker
    restart: on-failure

  postgres:
    image: postgres:14
    container_name: db
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: parser_db
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: on-failure